"""
Django settings for mmds_project project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/
"""

import os
from pathlib import Path
from dotenv import load_dotenv # .env untuk merahasiakan file penting

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

# --- KEAMANAN ---
SECRET_KEY = os.getenv('SECRET_KEY')

# Ambil dari .env, default ke False jika tidak ada
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# Sesuaikan dengan domain asli nanti
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(', ')

INSTALLED_APPS = [
    'jazzmin',
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    # App MMDS:
    'users',
    'perusahaan',
    'sistem',
    'operasional',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware', # request bhs lokal
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # tambahan mmds
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'mmds_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # folder template berisi html untuk sembunyikan sidebar kanan
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mmds_project.wsgi.application'

# --- DATABASE
# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
import dj_database_url # Opsional: sangat disarankan untuk parsing URL database

DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('DATABASE_URL'),
        engine='django.db.backends.postgresql'
    )
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/
from django.utils.translation import gettext_lazy as _ #kunci bahasa

LANGUAGE_CODE = 'id'
TIME_ZONE = 'Asia/Jakarta'

LANGUAGES = [
    ('id', _('Indonesian')),
]

USE_I18N = True # fitur bahasa
USE_L10N = True  # format waktu mengikuti lokal
USE_TZ = True # waktu UTC
USE_THOUSANDS_SEPARATOR = True

LANGUAGE_COOKIE_NAME = 'django_language'

# --- STATIC FILES ---
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATIC_URL = 'static/'

# CSS Custom buatan sendiri
STATICFILES_DIRS = [BASE_DIR / 'static',]

# output hasil "collectstatic" bawaan django
STATIC_ROOT = BASE_DIR / 'staticfiles'

# storage
AWS_ACCESS_KEY_ID = os.getenv('SUPABASE_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('SUPABASE_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = 'mmds_storage'
AWS_S3_ENDPOINT_URL = os.getenv('SUPABASE_S3_ENDPOINT')
AWS_S3_REGION_NAME = 'ap-southeast-1'
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None

STORAGES = {
    # Untuk Foto Nota & Bukti Transfer (Media)
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    # Untuk CSS & JS (Static) - Pakai WhiteNoise
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

JAZZMIN_SETTINGS = {
    "site_title": "Dayung Sari",
    "site_header": "Dayung Sari",
    "site_brand": "TukuData Software",
    "site_icon": "images/logo.png",
    "site_logo": "images/logo.jpg",
    "login_logo": "images/logo.png",
    "welcome_sign": "Selamat Datang di Dayung Sari",
    "copyright": "TukuData Ltd",
    "search_model": ["auth.User"],
    "custom_css": "login_custom.css",
    
    # Menu Samping
    "navigation_expanded": True,

    # icon
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.group": "fas fa-users",
        "perusahaan.departemen":"fas fa-building",
        "perusahaan.karyawan":"fas fa-users",
        "perusahaan.cabang":"fas fa-map-marker-alt",
        "operasional.lhcabang":"fas fa-receipt",
        "operasional.rekaplaporan":"fas fa-history",
        "sistem.aturanperusahaan":"fas fa-balance-scale",
    },
    
    # Urutan Menu Aplikasi
    "order_with_respect_to": [
        "auth",
        "auth.user",
        "auth.group", 
        
        "perusahaan", 
        "perusahaan.departemen",
        "perusahaan.karyawan",
        "perusahaan.cabang",

        "operasional", "sistem"],

    # kustomisasi tema
    "show_ui_builder":False,
}

JAZZMIN_UI_TWEAKS = {
    "body_small_text": True,
    "brand_colour": "navbar-primary",
    "accent": "accent-warning",
    "navbar": "navbar-primary navbar-dark",
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": True,
    "sidebar_nav_flat_style": True,
    "theme": "cyborg",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
}