# Generated by Django 6.0.1 on 2026-01-18 15:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perusahaan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LHCabang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('cabang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perusahaan.cabang')),
            ],
            options={
                'verbose_name_plural': 'Laporan Harian',
                'unique_together': {('cabang', 'tanggal')},
            },
        ),
        migrations.CreateModel(
            name='DetailLH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_kehadiran', models.CharField(choices=[('H', 'Hadir'), ('S', 'Sakit'), ('I', 'Izin'), ('A', 'Alfa')], default='H', max_length=1)),
                ('jam_berangkat', models.TimeField(blank=True, null=True)),
                ('adonan_bawa_gr', models.PositiveIntegerField(default=0, help_text='Dalam Gram')),
                ('jam_pulang', models.TimeField(blank=True, null=True)),
                ('adonan_sisa_gr', models.PositiveIntegerField(default=0, help_text='Dalam Gram')),
                ('nilai_sisa_rp', models.PositiveIntegerField(default=0, editable=False)),
                ('cash_diterima', models.PositiveIntegerField(default=0)),
                ('potongan_es', models.PositiveIntegerField(default=0)),
                ('potongan_gas', models.PositiveIntegerField(default=0)),
                ('potongan_obat', models.PositiveIntegerField(default=0)),
                ('potongan_qris', models.PositiveIntegerField(default=0)),
                ('target_minimal_rp', models.PositiveIntegerField(default=0, editable=False)),
                ('omzet_bruto_rp', models.PositiveIntegerField(default=0, editable=False)),
                ('selisih_rp', models.IntegerField(default=0, editable=False)),
                ('durasi_kerja', models.PositiveIntegerField(default=0, editable=False)),
                ('mitra', models.ForeignKey(limit_choices_to={'jabatan__icontains': 'mitra'}, on_delete=django.db.models.deletion.CASCADE, to='perusahaan.karyawan')),
                ('laporan_induk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_lh', to='operasional.lhcabang')),
            ],
            options={
                'verbose_name_plural': 'Detail LH',
            },
        ),
        migrations.CreateModel(
            name='PengeluaranLH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('OPERASIONAL', 'Operasional'), ('MAINTENANCE', 'Perbaikan Gerobak'), ('KASBON', 'Kasbon'), ('BONUS', 'Bonus Pekanan'), ('TRAINING', 'Uang Training'), ('KONSUMSI', 'Makan Bulanan'), ('LAINNYA', 'Lain-lain')], default='OPERASIONAL', max_length=20)),
                ('item', models.CharField(blank=True, help_text='Contoh: Air Galon / Kasbon Agus', max_length=100, null=True)),
                ('nominal', models.PositiveIntegerField(default=0)),
                ('bukti_nota', models.ImageField(blank=True, null=True, upload_to='nota_cabang/%Y/%m/')),
                ('laporan_induk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengeluaran_op', to='operasional.lhcabang')),
                ('mitra', models.ForeignKey(blank=True, help_text="Klik 'Save and Continue Editing' agar daftar mitra yang bertugas hari ini muncul.", limit_choices_to=models.Q(('jabatan__icontains', 'mitra'), ('jabatan__icontains', 'kepala cabang'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, to='perusahaan.karyawan')),
            ],
            options={
                'verbose_name_plural': 'Pengeluaran',
            },
        ),
        migrations.CreateModel(
            name='SetorPusat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cash_mitra', models.PositiveIntegerField(default=0, editable=False)),
                ('total_pengeluaran', models.PositiveIntegerField(default=0, editable=False)),
                ('nominal_setor', models.PositiveIntegerField(default=0, editable=False)),
                ('bukti_transfer', models.ImageField(upload_to='setoran_pusat/%Y/%m/')),
                ('laporan_induk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setoran_pusat', to='operasional.lhcabang')),
            ],
            options={
                'verbose_name_plural': 'Setor Harian',
            },
        ),
    ]
