# Generated by Django 6.0.1 on 2026-01-21 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operasional', '0001_initial'),
        ('perusahaan', '0002_karyawan_cabang_tugas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RekapLaporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Rekap Laporan',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='lhcabang',
            name='dibuat_oleh',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='detaillh',
            name='mitra',
            field=models.ForeignKey(limit_choices_to={'jabatan__icontains': 'mitra'}, on_delete=django.db.models.deletion.PROTECT, to='perusahaan.karyawan'),
        ),
    ]
