# Generated by Django 6.0.1 on 2026-01-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operasional', '0002_rekaplaporan_lhcabang_dibuat_oleh_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detaillh',
            old_name='potongan_obat',
            new_name='potongan_parkir',
        ),
        migrations.AlterField(
            model_name='setorpusat',
            name='nominal_setor',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='setorpusat',
            name='total_cash_mitra',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='setorpusat',
            name='total_pengeluaran',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
