# Generated by Django 6.0.1 on 2026-01-18 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AturanPerusahaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_aturan', models.CharField(default='Konfigurasi Utama', max_length=100)),
                ('konstanta_adonan_jadi', models.FloatField(default=2.5)),
                ('harga_per_gram_target', models.FloatField(default=92.0)),
                ('gaji_pokok_training', models.FloatField(default=1800000)),
                ('gaji_pokok_tetap', models.FloatField(default=2000000)),
                ('insentif_kehadiran', models.FloatField(default=150000)),
            ],
            options={
                'verbose_name_plural': 'Aturan Perusahaan',
            },
        ),
        migrations.CreateModel(
            name='TierBonusCabang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_mitra_berangkat', models.IntegerField()),
                ('nominal_bonus_cabang', models.FloatField()),
                ('aturan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_cabang', to='sistem.aturanperusahaan')),
            ],
        ),
        migrations.CreateModel(
            name='TierBonusMitra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_omset_harian', models.FloatField()),
                ('nominal_bonus_pekanan', models.FloatField()),
                ('aturan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_mitra', to='sistem.aturanperusahaan')),
            ],
        ),
    ]
