# Generated by Django 6.0.1 on 2026-01-18 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departemen',
            fields=[
                ('kode_departemen', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama_departemen', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Departemen',
            },
        ),
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id_staff', models.CharField(blank=True, help_text='ID Staff otomatis dibuatkan oleh sistem.', max_length=10, primary_key=True, serialize=False)),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('nomor_hp', models.CharField(max_length=15, unique=True)),
                ('jabatan', models.CharField(max_length=100)),
                ('tanggal_masuk', models.DateField()),
                ('status', models.CharField(choices=[('AKTIF', 'Aktif'), ('RESIGN', 'Resign'), ('CUTI', 'Cuti')], default='AKTIF', max_length=10)),
                ('alamat', models.TextField(blank=True, help_text='Opsional', null=True)),
                ('departemen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='perusahaan.departemen')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Karyawan',
            },
        ),
        migrations.CreateModel(
            name='Cabang',
            fields=[
                ('kode_cabang', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama_cabang', models.CharField(max_length=100, unique=True)),
                ('kepala_cabang', models.ForeignKey(blank=True, limit_choices_to={'jabatan__icontains': 'kepala cabang'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabang_dipimpin', to='perusahaan.karyawan')),
            ],
            options={
                'verbose_name_plural': 'Cabang',
            },
        ),
    ]
