# Generated by Django 6.0.1 on 2026-01-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perusahaan', '0002_karyawan_cabang_tugas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karyawan',
            name='alamat',
        ),
        migrations.AlterField(
            model_name='karyawan',
            name='nomor_hp',
            field=models.CharField(max_length=15),
        ),
    ]
